
# Nom du projet Supabase
project_id = "rdwqedmvzicerwotjseg"

[api]
# ID du projet pour les configurations spécifiques

[db]
# Configurations de la base de données

[functions.google-business]
verify_jwt = true
import_map = "./import_map.json"

[functions.secure-operations]
verify_jwt = true
import_map = "./import_map.json"

[functions.secure-client-config]
verify_jwt = false
import_map = "./import_map.json"

# Section pour variables d'environnement globales
