
# Nom du projet Supabase
project_id = "rdwqedmvzicerwotjseg"

[api]
# Configuration de l'API

[db]
# Configurations de la base de données

# Configurations des Edge Functions
[functions.login]
verify_jwt = false
import_map = "./import_map.json"

[functions.db]
verify_jwt = false  # Nous gérons l'authentification manuellement
import_map = "./import_map.json"

[functions.refresh-token]
verify_jwt = false
import_map = "./import_map.json"

[functions.utils]
verify_jwt = false
import_map = "./import_map.json"
